### ISSUE TITLE
ng-show is not working

### ISSUE THREAD

**Issue by phanhongphucit** [machineboy2045/angular-selectize#85] opened 2015-07-06 08:51 UTC
As the title described

**Comment by PhiLhoSoft** [comment] 2015-07-06 12:18
Indeed, it just adds a ng-hide class on the `selectize` tag, but it just adds `display: none` which is already on the tag...
I suppose the directive should watch this attribute and react accordingly.

Workaround: use `ng-if`. Not exactly the same thing, but might be useful in some cases. Since Angular removes the `selectize` component from the Dom, it effectively removes also the associated elements.

**Comment by Uelb** [comment] 2015-07-28 13:28
Same issue here... Thank you for the ng-if workaround

**Comment by mohitjee15** [comment] 2015-08-20 13:59
@PhiLhoSoft please close the issue if it resolved.

**Comment by PhiLhoSoft** [comment] 2015-08-20 22:21
@mohitjee15 I cannot: I haven't created the issue, and I have no control over the project.
Beside, the issue is not resolved. Support for ngShow can be added to the control, can be useful.

**Comment by machineboy2045** [comment] 2015-08-21 15:10
@PhiLhoSoft another solution might be to add a template to the directive, that would wrap a div around the div that Selectize gets applied to. What do you think?

**Closed** 2015-09-23 14:32 UTC
