### ISSUE TITLE
updating options not reflected in single selects

### ISSUE THREAD

**Issue by canebat** [machineboy2045/angular-selectize#71] opened 2015-05-12 07:41 UTC
```
$scope.options = [];
$scope.singleConfig = {
    options: $scope.options,
    maxItems: 1,
    sortField: 'text'
};

// later...
$scope.options = [{value: 'id1", text: 'A'}, {value: 'id2', text: 'B'}];
```

This will still display an empty select when the options get updated later. Does two-way binding not work for single selects? 

Using angular-selectize2 v1.2.1

**Comment by PhiLhoSoft** [comment] 2015-05-20 10:33
Duplicate of #55, see answer there.

**Closed** 2015-09-23 14:39 UTC
