### ISSUE TITLE
Case insensitive option for value field

### ISSUE THREAD

**Issue by nuno-mrks** [machineboy2045/angular-selectize#89] opened 2015-07-29 09:08 UTC
I'm facing a bit of a problem with a particular usage case of this directive.
I'm pushing options from a remote server and using the same property for both label and value fields. There are some instances where the currently selected option, **"option a"** may be served with a different case, such as **"Option A"**.
This results in the select element losing its current selected option (since the strings are different). This wouldn't happen if we had a flag like *ignoreValueCase* or something else, where the valueField could be evaluated without consideration of casing.

Is this somehow possible right now? If not, could you consider it for a future release?
Thank you

**Comment by PhiLhoSoft** [comment] 2015-08-03 10:24
Duplicate of https://github.com/brianreavis/selectize.js/issues/861 and indeed it is more a request for Selectize than for this wrapper.

**Comment by nuno-mrks** [comment] 2015-08-03 11:11
Yes, I had both repository pages opened at the time, and added the issue here by mistake.
Your code is barely touching the options, so it makes more sense to add the issue on the selectize.js repository instead of here.
Sorry for the misunderstanding.

**Comment by PhiLhoSoft** [comment] 2015-08-03 11:14
I suggest to close this one. Thanks.

**Closed** 2015-08-04 14:00 UTC
